### ISSUE TITLE
Invalid features in `concatenated_hdf5_data` are not ignored despite warning stating so.

### ISSUE THREAD

**Issue by maxschloegel** [DC-analysis/dcnum#27]
In the `concatenated_hdf5_data()` function that combines multiple hdf5-Datasets into one Virtual Dataset (VDS) invalid feature names are not ignored, even though the warning says it does. I.e. if one of the features defines a sub-group instead of a dataset in the root-group, it will throw an error a few lines later:
```shell
ERROR tests/test_utils_data.py - AttributeError: 'Group' object has no attribute 'shape'
```
See the following lines here:

https://github.com/DC-analysis/dcnum/blob/41579a85b7f79b79f9f5d44ac0c8db3a8505900a/src/dcnum/read/hdf5_data.py#L431-L434

A fix would be to include a `continue` statement after throwing a warning, so the invalid features are actually skipped.

TODO:
- [x] Add `continue` statement
- [x] Write tests that check for correct skipping of events

**Comment by maxschloegel** [comment]
@paulmueller feel free to assign me here!

**Comment by paulmueller** [comment]
You are correct. There is a `continue` statement missing and tests based on the `contour` feature would be very welcome.
