### ISSUE TITLE
optimize code for inert_ratio_prnc and tilt features

### ISSUE THREAD

**Issue by SaraKaliman** [DC-analysis/dcnum#6]
I suggest using formula for calculating principal component inertia ratio and tilt to optimize processing speed: 

For raw contour:

Ixx = np.float64(mu_raw["mu02"])
Iyy = np.float64(mu_raw["mu20"])
Ixy = np.float64(mu_raw["mu11"])
# Moments of Inertia / Central moments in principal axes
I1 = 0.5*(Ixx+Iyy + np.sqrt((Ixx - Iyy) ** 2 + 4*(Ixy ** 2)))
I2 = 0.5*(Ixx+Iyy - np.sqrt((Ixx - Iyy) ** 2 + 4*(Ixy ** 2)))
inert_ratio_prnc = np.sqrt(I1/I2)

# tilt angle in radians
tilt = 0.5 * np.arctan2(-2*Ixy, Iyy - Ixx)

**Comment by paulmueller** [comment]
Thanks for creating the issue. I transferred it to the dcnum repository. Are you planning to create a PR?

The relevant code would be here: https://github.com/DC-analysis/dcnum/blob/main/dcnum/feat/feat_moments/mt_legacy.py

**Comment by paulmueller** [comment]
Those are implemented in 0.12.2
